import type { Metadata } from "next";
import "./globals.css";
import BackendStatus from "../src/component/BackendStatus";
<<<<<<< HEAD
import { AuthProvider } from "../src/contexts/AuthContext";
import { NotificationProvider } from "../src/contexts/NotificationContext";
import { OfflineSyncProvider } from "../src/contexts/OfflineSyncContext";

export const metadata: Metadata = {
  title: "MoveMonitor — IoT Tracking",
  description: "Hệ thống giám sát hành trình và phát hiện va chạm thời gian thực",
=======

export const metadata: Metadata = {
  title: "Moni Move",
  description: "Generated by IoT-Team",
>>>>>>> f72d72325236dd648406a88ee667af6334effd3a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="vi" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <NotificationProvider>
            {/* OfflineSyncProvider — singleton, chạy 1 lần toàn app */}
            <OfflineSyncProvider>
              {children}
            </OfflineSyncProvider>
            <BackendStatus />
          </NotificationProvider>
        </AuthProvider>
=======
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <BackendStatus />
>>>>>>> f72d72325236dd648406a88ee667af6334effd3a
      </body>
    </html>
  );
}
