import type { Metadata } from "next";
import "./globals.css";
import BackendStatus from "../src/component/BackendStatus";

export const metadata: Metadata = {
  title: "Moni Move",
  description: "Generated by IoT-Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <BackendStatus />
      </body>
    </html>
  );
}
